name: AppImage
on: [push, pull_request]

jobs:
  Generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      LINUX_TAG: manylinux2010
      PYTHON_VERSION: "3.10"

    steps:
    - name: Checkout base repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        pip install python-appimage

    - name: Build
      run: |
        python-appimage build app -p ${PYTHON_VERSION} appimage
        ls ./

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: continuous
        title: Continuous build
        files: python-x86_64.AppImage
        repo_token: ${{ secrets.GITHUB_TOKEN }}